name: nightly-tests
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸Ivy Vision
        uses: actions/checkout@v2
        with:
          path: vision
          persist-credentials: false

      - name: Run Tests
        run: |
          cd vision
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          docker run --rm -v `pwd`:/vision unifyai/vision:latest python3 -m pytest ivy_vision_tests/
